#!/usr/bin/env bash

# Get variables from configuration file
source /usr/local/bin/3GWebcam-conf.sh

#/sbin/ifconfig eth0 down
wvdial pin >/dev/null 2>&1 &
echo "pin"
sleep 5
wvdial BYou >/dev/null 2>&1 &
echo "connecting..."
